### ISSUE TITLE
Data Analysis

### ISSUE THREAD

**Issue by rossellaaversa** [Materials-Data-Science-and-Informatics/MDMC-NEP-top-level-ontology#17]
According to the glossary, Data Analysis includes Data Processing, Correlative Characterization, and Data Interpretation.
In the STM use case, "Image Selection and Retrievement", "Image labelling process" and "Metadata Selection" are included in Data Processing. 

Data Analysis can be superclass of Data Processing and Correlative Characterization?
BUT Data Interpretation must be outside the superclass, as it does NOT generate analysed data (only intepretation)

To check: is Correlative Characterization using ONLY raw data or it can happen that is uses also analysed data?
If it uses also analysed data, it cannot be in the superclass of Data Analysis.

**Comment by az-ihsan** [comment]
as of 01.02.2022 in the ontology we have 
```
DataProcessing: prov:Activity
    prepared some CorrelativeCharacterization
 prov:used some RawData

DataAnalysis: prov:Activity
    prov:wasAssociatedWith some DataAnalysisSoftware
    prov:used some RawData
    prov:wasAssociatedWith some ResearchUser

AnalysedData: ResearchData
    prov:wasGeneratedBy some DataAnalysis
    hasMetadata some Metadata

CorrelativeCharacterization: prov:Activity
    prov:wasAssociatedWith some ResearchUser
```

**Comment by rossellaaversa** [comment]
`DataAnalysis` and `AnalysedData` sound perfect to me. 
- `DataProcessing` needs further discussion: this is the preprocessing that can be made in order to prepare data to be analysed, so not only for correlative characterization. 
- as agreed today, `CorrelativeCharacterization` needs to be better defined.
@az-ihsan please let's ask this two things tomorrow to the other members of the Metadata WG

**Comment by az-ihsan** [comment]
Based on the MDMC meeting on 03.01.2022, 
1. `DataInterpretation` is not part of `DataAnalysis`, but when we merge the result of e.g., Correlative Characterisation we do a `DataInterpretation`
2. `CorrelativeCharacterisation` could use both `RawData` and `AnalysedData`

**Comment by rossellaaversa** [comment]
Everything depends on how we want to define terms. 
If we adopt the CASRAI definition of "Data analysis – A data lifecycle stage that involves the techniques that produce synthesized knowledge from organized information", the lifecycle will include everything: data processing, data analysis itself, data interpretation, correlative characterization. 

If instead we use our glossary, and maybe rearrange some terms, we could have:

```
DataProcessing: prov:Activity
 prov:used some RawData
    prov:wasAssociatedWith some Software
    prov:wasAssociatedWith some ResearchUser

DataAnalysis: prov:Activity
    prov:wasAssociatedWith some DataAnalysisSoftware
    prov:used some RawData
    prov:used some ProcessedData
    prov:wasAssociatedWith some ResearchUser

ProcessedData: ResearchData
    prov:wasGeneratedBy some DataProcessing
    hasMetadata some Metadata

AnalysedData: ResearchData
    prov:wasGeneratedBy some DataAnalysis
    hasMetadata some Metadata

CorrelativeCharacterization: prov:Activity
    prov:wasAssociatedWith some ResearchUser
    prov:used some RawData
    prov:wasGeneratedBy some DataProcessing
    prov:used some ProcessedData
    prov:wasGeneratedBy some DataAnalysis
    prov:used some AnalysedData
    hasMetadata some Metadata

DataInterpretation: pro:Activity
    prov:wasAssociatedWith some ResearchUser
    prov:used some AnalysedData
    prov:used some Reference
    hasMetadata some Metadata
```
This makes things a bit more complicated and fine-grained. 
What do you think? @az-ihsan @mpanighel @MehrdadJalali-KIT @EOsmenaj

**Comment by az-ihsan** [comment]
> Everything depends on how we want to define terms. If we adopt the CASRAI definition of "Data analysis – A data lifecycle stage that involves the techniques that produce synthesized knowledge from organized information", the lifecycle will include everything: data processing, data analysis itself, data interpretation, correlative characterization.
> 
> If instead we use our glossary, and maybe rearrange some terms, we could have:
> 
> ```
> DataProcessing: prov:Activity
>  prov:used some RawData
>     prov:wasAssociatedWith some Software
>     prov:wasAssociatedWith some ResearchUser
> 
> DataAnalysis: prov:Activity
>     prov:wasAssociatedWith some DataAnalysisSoftware
>     prov:used some RawData
>     prov:used some ProcessedData
>     prov:wasAssociatedWith some ResearchUser
> 
> ProcessedData: ResearchData
>     prov:wasGeneratedBy some DataProcessing
>     hasMetadata some Metadata
> 
> AnalysedData: ResearchData
>     prov:wasGeneratedBy some DataAnalysis
>     hasMetadata some Metadata
> 
> CorrelativeCharacterization: prov:Activity
>     prov:wasAssociatedWith some ResearchUser
>     prov:used some RawData
>     prov:wasGeneratedBy some DataProcessing
>     prov:used some ProcessedData
>     prov:wasGeneratedBy some DataAnalysis
>     prov:used some AnalysedData
>     hasMetadata some Metadata
> 
> DataInterpretation: pro:Activity
>     prov:wasAssociatedWith some ResearchUser
>     prov:used some AnalysedData
>     prov:used some Reference
>     hasMetadata some Metadata
> ```
> 
> This makes things a bit more complicated and fine-grained. What do you think? @az-ihsan @mpanighel @MehrdadJalali-KIT @EOsmenaj

Hi Rosella, thanks for putting this. I see the `ProcessedData` has not been defined in our glossary which i think that doesnt necessary to be defined since i think the this processed data is similar to `AnalysedData` in our term. If this is the case we can really simplify the approach above because there is no intermediate step as defined in `ProcessedData`:
```
DataAnalysis: prov:Activity
    prov:used some RawData
    prov:wasAssociatedWith some DataAnalysisSoftware
    prov:wasAssociatedWith some ResearchUser

DataProcessing: DataAnalysis
CorrelativeCharacterization: DataAnalysis

DataInterpretation: prov:Activity
    prov:used some AnalyzedData
```

The `AnalyzedData` could be a superclass of processed data, correlative characterization data, etc if they want to be defined later on.

**Comment by rossellaaversa** [comment]
According to @mpanighel data analysis is whatever you do after the measurement, using raw data, up to publication. See https://en.wikipedia.org/wiki/Data_analysis#The_process_of_data_analysis

@EOsmenaj posted also: https://sisu.ut.ee/rdm_course1/data-collection-processing-and-analysis

All the definitions make clear that *data analysis is a big container of other activities* 
What we are missing is a definition of the proper "data analysis" within the data analysis superclass. 
--> to decide. 
Exploratory data analysis?


@MehrdadJalali-KIT is suggesting to use the property `participateIn` to say that e.g. data processing participateIn data analysis. We can evaluate this possibility.

**Comment by rossellaaversa** [comment]
Temporary definitions:

**Data Analysis Lifecycle**
The process of systematically performing actions and methods, e.g. statistical and/or logical techniques, on Research Data in order to produce synthesized knowledge to, e.g., detect patterns, determine relationships, develop explanations, test hypotheses, prove theories, suggest conclusions.
Data Analysis includes (but is not limited to): Data Processing, Data Analysis, Data Interpretation. These actions may be iterative and may be combined in chains or workflows.

**Data Processing**
Data treatment performed on Raw Data to prepare it for another procedure of the Data Analysis Lifecycle, e.g., Data Analysis or Data Interpretation. It usually consists of routine actions. It may include: sampling, filtering, de-noising, transformation, fusion or compression of existing data, as well as calibration, normalization, statistical data reduction, background subtraction, correction of artifacts. 

**Data Analysis**
The process of collecting, modeling, and analyzing Research Data to extract insights that support the answer to some specific research question. Data Analysis may be performed using Data Analysis Software. It may include: linear combination, data fitting, data modeling, pattern extraction. 

**Data Interpretation**
The process of assigning meaning to the collected information, after an analytical and/or experimental Study, and determining the conclusions, significance, and implications of research findings, possibly in comparison with a predefined reference. 

**Correlative Characterization**
The identifiable action of describing one or more Samples (depending on the particular research context) and connecting the different types of information from co-referenced (in time or space) multi-dimensional Research Data. This may include using multiple Measurement Techniques to obtain complementary insights for a region of interest, as well as putting into relation features and properties of different Sample areas across multiple length scales or over time.

**Comment by rossellaaversa** [comment]
Suggestion of @MehrdadJalali-KIT : Data Analysis Lifecycle as **container**

**Comment by MehrdadJalali-KIT** [comment]
> Temporary definitions:
> 
> **Data Analysis Lifecycle** The process of systematically performing actions and methods, e.g. statistical and/or logical techniques, on Research Data in order to produce synthesized knowledge to, e.g., detect patterns, determine relationships, develop explanations, test hypotheses, prove theories, suggest conclusions. Data Analysis includes (but is not limited to): Data Processing, Data Analysis, Data Interpretation. These actions may be iterative and may be combined in chains or workflows.
> 
> **Data Processing** Data treatment performed on Raw Data to prepare it for another procedure of the Data Analysis Lifecycle, e.g., Data Analysis or Data Interpretation. It usually consists of routine actions. It may include: sampling, filtering, de-noising, transformation, fusion or compression of existing data, as well as calibration, normalization, statistical data reduction, background subtraction, correction of artifacts.
> 
> **Data Analysis** The process of collecting, modeling, and analyzing Research Data to extract insights that support the answer to some specific research question. Data Analysis may be performed using Data Analysis Software. It may include: linear combination, data fitting, data modeling, pattern extraction.
> 
> **Data Interpretation** The process of assigning meaning to the collected information, after an analytical and/or experimental Study, and determining the conclusions, significance, and implications of research findings, possibly in comparison with a predefined reference.
> 
> **Correlative Characterization** The identifiable action of describing one or more Samples (depending on the particular research context) and connecting the different types of information from co-referenced (in time or space) multi-dimensional Research Data. This may include using multiple Measurement Techniques to obtain complementary insights for a region of interest, as well as putting into relation features and properties of different Sample areas across multiple length scales or over time.

Data Analysis includes Data Analysis?? In paragraph 2 of Data Analysis Life Cycle.

**Comment by MehrdadJalali-KIT** [comment]
Can we say that Data Interpretation, Data Processing and Correlative Characterization are member of Data Analysis ?

[[http://owlgred.lumii.lv/online_visualization/ixbh](http://owlgred.lumii.lv/online_visualization/ixbh#)](url)

**Comment by rossellaaversa** [comment]
> > Temporary definitions:
> > **Data Analysis Lifecycle** The process of systematically performing actions and methods, e.g. statistical and/or logical techniques, on Research Data in order to produce synthesized knowledge to, e.g., detect patterns, determine relationships, develop explanations, test hypotheses, prove theories, suggest conclusions. Data Analysis includes (but is not limited to): Data Processing, Data Analysis, Data Interpretation. These actions may be iterative and may be combined in chains or workflows.
> > **Data Processing** Data treatment performed on Raw Data to prepare it for another procedure of the Data Analysis Lifecycle, e.g., Data Analysis or Data Interpretation. It usually consists of routine actions. It may include: sampling, filtering, de-noising, transformation, fusion or compression of existing data, as well as calibration, normalization, statistical data reduction, background subtraction, correction of artifacts.
> > **Data Analysis** The process of collecting, modeling, and analyzing Research Data to extract insights that support the answer to some specific research question. Data Analysis may be performed using Data Analysis Software. It may include: linear combination, data fitting, data modeling, pattern extraction.
> > **Data Interpretation** The process of assigning meaning to the collected information, after an analytical and/or experimental Study, and determining the conclusions, significance, and implications of research findings, possibly in comparison with a predefined reference.
> > **Correlative Characterization** The identifiable action of describing one or more Samples (depending on the particular research context) and connecting the different types of information from co-referenced (in time or space) multi-dimensional Research Data. This may include using multiple Measurement Techniques to obtain complementary insights for a region of interest, as well as putting into relation features and properties of different Sample areas across multiple length scales or over time.
> 
> @rossellaaversa Data Analysis includes Data Analysis?? In paragraph 2 of Data Analysis Life Cycle.

@az-ihsan  it's a typo, of course. Data Analysis Lifecycle includes...

**Comment by rossellaaversa** [comment]
> Can we say that Data Interpretation, Data Processing and Correlative Characterization are member of Data Analysis ?
> 
> [[http://owlgred.lumii.lv/online_visualization/ixbh](http://owlgred.lumii.lv/online_visualization/ixbh#)](url)

according to our last Metadata meeting on last Wednesday, we agreed on having correlative characterization as a PURPOSE rather than a specific action. Thus, I would suggest to exclude it from the ontology

**Comment by az-ihsan** [comment]
> Can we say that Data Interpretation, Data Processing and Correlative Characterization are member of Data Analysis ?
> 
> [[http://owlgred.lumii.lv/online_visualization/ixbh](http://owlgred.lumii.lv/online_visualization/ixbh#)](url)

Looking to the graph you made, i think the use of `memberOf` makes sense to me. A minor edit, could you put the `DataAnalysisLifecycle` as the container rather than `DataAnalysis` and make the `DataAnalysis` member of `DataAnalysisLifecycle`?

**Comment by az-ihsan** [comment]
> > Can we say that Data Interpretation, Data Processing and Correlative Characterization are member of Data Analysis ?
> > [[http://owlgred.lumii.lv/online_visualization/ixbh](http://owlgred.lumii.lv/online_visualization/ixbh#)](url)
> 
> according to our last Metadata meeting on last Wednesday, we agreed on having correlative characterization as a PURPOSE rather than a specific action. Thus, I would suggest to exclude it from the ontology

I see, then we can remove the `CorrelativeCharacterization` class

**Comment by rossellaaversa** [comment]
Now it sounds great: data processing, data analysis, data interpretation are memberOf data analysis lifecycle. Thanks @MehrdadJalali-KIT!

**Comment by az-ihsan** [comment]
Hi, i have question regarding the Data Interpretation, is there any entity that is generated by by the data interpretation? like the one in Data Analysis which generated Analyzed data?

**Comment by EOsmenaj** [comment]
I think the entity generated by data interpretation can be: data interpretation results or conclusions.

**Comment by rossellaaversa** [comment]
I agree: I would also say conclusions

**Comment by az-ihsan** [comment]
implemented issue closed
