### ISSUE TITLE
Sample Carrier 

### ISSUE THREAD

**Issue by az-ihsan** [Materials-Data-Science-and-Informatics/MDMC-NEP-top-level-ontology#20]
Hi, i came across this while editing the ontology. 

Is the sample carrier equipment? can we say that sample carrier is a subclass of equipment rather than entity?

**Comment by mpanighel** [comment]
I would say sample carrier can be considered equipment

**Comment by rossellaaversa** [comment]
I agree with @mpanighel: sample carrier is part of equipment

**Comment by az-ihsan** [comment]
close the issue according to #38
