### ISSUE TITLE
Study and Project 

### ISSUE THREAD

**Issue by az-ihsan** [Materials-Data-Science-and-Informatics/MDMC-NEP-top-level-ontology#3]
I would suggest not to take the **Study** term as a subclass of the **Project** because:

1. Based on the definition Project is planned to perform Study. In the active sentence, Study performs Project
2. One instance of Project would have e.g. 10 members of Research User, if the Study as subclass of Project, then all those 10 members also performed an instance of Study. This will violate a Project that consists of at least one or more Study with the division of Research User take part in a study, e.g. 5 Persons in study_1 and another 5 persons in study_2

**Comment by az-ihsan** [comment]
After the discussion with @rossellaaversa and @MehrdadJalali-KIT on 16.11, we decided that the class of `Study` and `Project` is connected by an `ObjectProperty`

Thus, at least as of now
```
Study: performs some Project
```

**Comment by rossellaaversa** [comment]
Just to be precise: it's not the Project to perform Study, nor Study to perform Project. 
Project is a group of one or more Research Users
Users performs Study (which in turn is a group of one or more Experiment, which in turn is a group of one or more Measurement)

**Comment by rossellaaversa** [comment]
So I would formalise it saying that a Research User must have a Project s/he belongs to

**Comment by rossellaaversa** [comment]
Project is a class (superclass of Study)
We can say that a Research User: hasProject Project

**Comment by az-ihsan** [comment]
```
Project: Research User
perform some Study
```

**Comment by rossellaaversa** [comment]
Project: Research User
perform a common Study

**Comment by az-ihsan** [comment]
Project:ResearchUser
hasStudy some Study

**Comment by rossellaaversa** [comment]
This must be checked in Protege @az-ihsan

**Comment by az-ihsan** [comment]
I re-opened the issue as @mpanighel raised a question on how project is subclass of research user. after thinking again, i think this should be discussed once more. :)

**Comment by rossellaaversa** [comment]
> I would suggest not to take the **Study** term as a subclass of the **Project** because:
> 
> 1. Based on the definition Project is planned to perform Study. In the active sentence, Study performs Project
> 2. One instance of Project would have e.g. 10 members of Research User, if the Study as subclass of Project, then all those 10 members also performed an instance of Study. This will violate a Project that consists of at least one or more Study with the division of Research User take part in a study, e.g. 5 Persons in study_1 and another 5 persons in study_2

To clarify: a `Project` is a group of `Research User` (who group together into the `Project`, indeed) with the purpose of performing one or more `Study`. According to my interpretation of the definition, ALL the `Research User` work on the same set `Study`. 
Following this interpretation, if a subgroup of users want to perform other studies, on another topic, they should be an other `Project`. A user can be member of multiple projects. 

Let's start from here tomorrow. @az-ihsan

**Comment by az-ihsan** [comment]
How about if we change the project to this?

```
Project:Entity
Project prov:wasAttributedWith ResearchUser
Project hasStudy some Study
```

**Comment by az-ihsan** [comment]
close the issue according to #38 and the discussion on 29.03.2022
