### ISSUE TITLE
[Use-case] STM typical Experiment example

### ISSUE THREAD

**Issue by mpanighel** [Materials-Data-Science-and-Informatics/MDMC-NEP-top-level-ontology#46]
Instrument Scientist mounts the Sample Component _Ni substrate_ on a Sample Holder.

Sample Holder is inserted it into the preparation chamber to perform the Sample Preparation in different steps:
* Sample Component _Ni substrate_ undergoes _sputtering_ step with the Equipment _Sputter gun_
* Sample Component _Ni substrate_ undergoes _annealing_ step with the Equipment _Heating stage_
* In the _dosing_ step, Sample Component _ethylene_ is dosed on the _Ni substrate_ with the Equipment _Gas line_ to produce graphene.

The Instrument _LEED_ is used to perform a Measurement to check the Sample quality.
The obtained Sample _Gr_Ni_ is placed in the Instrument _VT-STM_ to perform the Measurement.

**Comment by az-ihsan** [comment]
Thanks @mpanighel, ill take a look into this and map into our ontology. We can discuss again in the next meeting.

**Comment by az-ihsan** [comment]
> Sample Component *ethylene* is dosed on the Ni *substrate* with the Equipment Gas *line* to produce graphene.
What is the process name of this?

**Comment by az-ihsan** [comment]
> Sample Holder is inserted it into the preparation chamber to perform the Sample Preparation in different steps:
> * Ni substrate undergoes sputtering step with the Equipment Sputter gun
> * Ni substrate undergoes annealing step with the equipment Heating stage
> * Sample Component ethylene is dosed on the Ni substrate with the Equipment Gas line to produce graphene.

CMIIW, the result of the sample preparation is *graphene*?

**Comment by az-ihsan** [comment]
Can we say Graphene was derived from a sample that has Ni component in it?

**Comment by mpanighel** [comment]
> > Sample Component _ethylene_ is dosed on the Ni _substrate_ with the Equipment Gas _line_ to produce graphene.
> 
> What is the process name of this?

I would call it _dosing_

**Comment by mpanighel** [comment]
> CMIIW, the result of the sample preparation is _graphene_ sample?

We can name the Sample _Gr_Ni_ (edited the main comment)

**Comment by mpanighel** [comment]
> Can we say Graphene was derived from a sample that has Ni component in it?

This is tricky. Graphene itself is a part of the final Sample _Gr_Ni_ but it is not a Sample Component. We can say _graphene_ was derived from two Sample Components during Sample preparation (as it is for a Sample), but still _graphene_ it is not a Sample.

**Comment by az-ihsan** [comment]
> Instrument Scientist mounts the Sample Component _Ni substrate_ on a Sample Holder.
> 
> Sample Holder is inserted it into the preparation chamber to perform the Sample Preparation in different steps:
> 
> * Sample Component _Ni substrate_ undergoes _sputtering_ step with the Equipment _Sputter gun_
> * Sample Component _Ni substrate_ undergoes _annealing_ step with the Equipment _Heating stage_
> * In the _dosing_ step, Sample Component _ethylene_ is dosed on the _Ni substrate_ with the Equipment _Gas line_ to produce graphene.
> 

In the Sample Preparation above, can we say that this is an order process or at least there is no parallel process in each sub-process, e.g., sputtering, annealing, and dosing?

**Comment by az-ihsan** [comment]
After the modularization, there is a need to revisit agan the mapping.

**Comment by az-ihsan** [comment]
closed by #68
