### ISSUE TITLE
Sub-activity of DataAnalysisLifecycle

### ISSUE THREAD

**Issue by az-ihsan** [Materials-Data-Science-and-Informatics/MDMC-NEP-top-level-ontology#48]
On 13.09.2022, we had a discussion on whether we change the property related to `DataAnalysisLifeCycle` and its sub-activity `DataProcessing`, `DataAnalysis`, `DataInterpretataion`. At the moment the usage of `isMemberOf` is ambiguous with the 'prov:hadMember' that relates the `entity:Collection` to its entity member. 

After reading the PROV documents again, one [FAQ](https://www.w3.org/2001/sw/wiki/PROV-FAQ#How_can_I_define_a_sub_activity.3F) suggests that we can use `dcterms:hasPart` to relates the activity e.g., `DataAnalysisLifeCycle` with its sub-activities. 

Thus, 

```
`DataAnalysisLifeCycle` dcterms:hasPart some` `DataProcessing`
`DataAnalysisLifeCycle` dcterms:hasPart some` `DataAnalysis`
`DataAnalysisLifeCycle` dcterms:hasPart some` `DataInterpretataion`
```

**Comment by az-ihsan** [comment]
Can you @mpanighel @rossellaaversa @MehrdadJalali-KIT @EOsmenaj give some comments on this?

**Comment by MehrdadJalali-KIT** [comment]
Logically, it makes sense to me.

**Comment by EOsmenaj** [comment]
It's ok for me to use Dublin core term: hasPart to relate:
 `DataAnalysisLifeCycle` dcterms:hasPart ->` `DataProcessing`
`DataAnalysisLifeCycle` dcterms:hasPart ->` `DataAnalysis`
`DataAnalysisLifeCycle` dcterms:hasPart ->` `DataInterpretataion` 

In addition, in our example, I propose to use even the inverse term:isPartOf that relates each sub-activity with the 'DataAnalysisLifecycle':
 `DataProcessing` dcterms :isPartOf ->` `DataAnalysisLifeCycle`
` `DataAnalysis` dcterms: isPartOf -> ` `DataAnalysisLifeCycle`
 ` `DataInterpretataion` dcterms: isPartOf -> ` `DataAnalysisLifeCycle`

**Comment by az-ihsan** [comment]
> It's ok for me to use Dublin core term: hasPart to relate: `DataAnalysisLifeCycle` dcterms:hasPart ->`DataProcessing` `DataAnalysisLifeCycle` dcterms:hasPart ->`DataAnalysis` `DataAnalysisLifeCycle` dcterms:hasPart -> `DataInterpretation`
> 
> In addition, in our example, I propose to use even the inverse term:isPartOf that relates each sub-activity with the 'DataAnalysisLifecycle': `DataProcessing` dcterms :isPartOf ->`DataAnalysisLifeCycle` `DataAnalysis` dcterms: isPartOf -> `DataAnalysisLifeCycle` `DataInterpretation` dcterms: isPartOf -> `DataAnalysisLifeCycle`

Sure, we can also put the inverse in the property.
