### ISSUE TITLE
[Discussion] Ontology name

### ISSUE THREAD

**Issue by az-ihsan** [Materials-Data-Science-and-Informatics/MDMC-NEP-top-level-ontology#7]
Please think about the fancy name of ontology
with these points in mind

* We would like to use this as a core ontology metadata that could be extended to some particular experiment
* It consists of organization, experiment activity, data
* We implemented the provenance data according to ProvO

**Comment by az-ihsan** [comment]
Correlative Characterization Prov -> CCProv

**Comment by az-ihsan** [comment]
Based on the discussion on 16.11, @rossellaaversa will also suggest a name for ontology name

**Comment by rossellaaversa** [comment]
alternative: WE-Prov: Workflow of Experiments Provenance

**Comment by MehrdadJalali-KIT** [comment]
WEO

**Comment by rossellaaversa** [comment]
Please note that, as correctly pointed by @az-ihsan, Experiment does not include Analysis, so probably is not the best word to use...

**Comment by MehrdadJalali-KIT** [comment]
It may be said that it totally depends on the aim of the creating ontology, For example, if the purpose is correlative characterization in materials science, the name I may recommend is correlative material characterization ontology, or **CMC** Ontology.

**Comment by az-ihsan** [comment]
We will discuss with the MDMC group about the name. The candidate would:
1. CMCO: Correlative Materials Characterization Ontology

**Comment by az-ihsan** [comment]
hint:
* Research 
* Workflow
* Materials
-> Materials Research Workflow Ontology (MaReW)

**Comment by MehrdadJalali-KIT** [comment]
Materials Research Ontology (MatRes)

**Comment by az-ihsan** [comment]
Mirco: "what makes the ontology difference? in it is peculiarity?
* data analysis lifecycle
* measurements of experiment
* management level ontology--core"

Mehrdad: Provenance information ontology for materials science (PRIMO)

**Comment by az-ihsan** [comment]
after I cheked with prefix.cc, the prefix/name PRIMO is available to use. So we are good to go if we use PRIMO prefix.

**Comment by rossellaaversa** [comment]
PRIMO is ok, but it should stay for PRovenance Information for Materials Science Ontology. 
An alternative is PRIMA (Provenance Information for MAterials science).

**Comment by az-ihsan** [comment]
Hi Rossella, 

For me PRIMA sounds Prima (--great in DE)! Then, sure I can vote for this as well. 

Then we agree on this name? how about this @MehrdadJalali-KIT? @mpanighel?
